export const PERMISSIONS = [
  { key: 'dashboard:view', label: 'View Dashboard', group: 'Dashboard' },
  { key: 'contacts:view', label: 'View Contacts', group: 'Contacts' },
  { key: 'contacts:create', label: 'Create Contacts', group: 'Contacts' },
  { key: 'contacts:update', label: 'Update Contacts', group: 'Contacts' },
  { key: 'contacts:delete', label: 'Delete Contacts', group: 'Contacts' },
  { key: 'leads:view', label: 'View Leads', group: 'Lead Generation' },
  { key: 'leads:manage', label: 'Manage Leads & Forms', group: 'Lead Generation' },
  { key: 'leads:import', label: 'Import Leads', group: 'Lead Generation' },
  { key: 'deals:view', label: 'View Deals', group: 'Deals' },
  { key: 'deals:create', label: 'Create Deals', group: 'Deals' },
  { key: 'deals:update', label: 'Update Deals', group: 'Deals' },
  { key: 'deals:delete', label: 'Delete Deals', group: 'Deals' },
  { key: 'quotations:view', label: 'View Quotations', group: 'Quotations' },
  { key: 'quotations:create', label: 'Create Quotations', group: 'Quotations' },
  { key: 'quotations:update', label: 'Update Quotations', group: 'Quotations' },
  { key: 'quotations:delete', label: 'Delete Quotations', group: 'Quotations' },
  { key: 'tasks:view', label: 'View Tasks', group: 'Tasks' },
  { key: 'tasks:create', label: 'Create Tasks', group: 'Tasks' },
  { key: 'tasks:update', label: 'Update Tasks', group: 'Tasks' },
  { key: 'tasks:delete', label: 'Delete Tasks', group: 'Tasks' },
  { key: 'documents:view', label: 'View Documents', group: 'Documents' },
  { key: 'documents:create', label: 'Upload Documents', group: 'Documents' },
  { key: 'documents:delete', label: 'Delete Documents', group: 'Documents' },
  { key: 'internships:view', label: 'View Internships', group: 'Internships' },
  { key: 'internships:create', label: 'Create Internships', group: 'Internships' },
  { key: 'internships:update', label: 'Update Internships', group: 'Internships' },
  { key: 'internships:delete', label: 'Delete Internships', group: 'Internships' },
  { key: 'jobs:view', label: 'View Find Jobs', group: 'Find Jobs' },
  { key: 'jobs:manage', label: 'Manage / Save Jobs', group: 'Find Jobs' },
  { key: 'ats:view', label: 'View ATS Scanner', group: 'ATS Scanner' },
  { key: 'ats:scan', label: 'Scan Resumes', group: 'ATS Scanner' },
  { key: 'resumebuilder:view', label: 'View Resume Builder', group: 'Resume Builder' },
  { key: 'resumebuilder:build', label: 'Build & Optimize Resumes', group: 'Resume Builder' },
  { key: 'seo:view', label: 'View SEO Analysis', group: 'SEO Analysis' },
  { key: 'seo:scan', label: 'Run SEO Scans', group: 'SEO Analysis' },
  { key: 'alertsms:view', label: 'View Alert SMS', group: 'Alert SMS' },
  { key: 'alertsms:send', label: 'Send Alert SMS', group: 'Alert SMS' },
  { key: 'alertsms:delete', label: 'Delete Alert SMS Logs', group: 'Alert SMS' },
  { key: 'automation:view', label: 'View Automation', group: 'Automation' },
  { key: 'automation:manage', label: 'Manage Automation', group: 'Automation' },
  { key: 'analytics:view', label: 'View Analytics', group: 'Analytics' },
  { key: 'loadtest:view', label: 'View Load Tests', group: 'Load Testing' },
  { key: 'loadtest:run', label: 'Run Load Tests', group: 'Load Testing' },
  { key: 'loadtest:delete', label: 'Delete Load Tests', group: 'Load Testing' },
  { key: 'security:view', label: 'View Security Analytics', group: 'Security' },
  { key: 'security:scan', label: 'Run Security Scans', group: 'Security' },
  { key: 'security:delete', label: 'Delete Security Scans', group: 'Security' },
  { key: 'sechub:view', label: 'View Security Hub', group: 'Security' },
  { key: 'portscan:view', label: 'View Port Scans', group: 'Port Scan' },
  { key: 'portscan:run', label: 'Run Port Scans', group: 'Port Scan' },
  { key: 'portscan:delete', label: 'Delete Port Scans', group: 'Port Scan' },
  { key: 'network:view', label: 'View Network Devices', group: 'Network' },
  { key: 'network:run', label: 'Scan Network Devices', group: 'Network' },
  { key: 'network:delete', label: 'Delete Network Scans', group: 'Network' },
  { key: 'dnssec:view', label: 'View DNS Security', group: 'DNS Security' },
  { key: 'dnssec:run', label: 'Run DNS Scans', group: 'DNS Security' },
  { key: 'dnssec:delete', label: 'Delete DNS Scans', group: 'DNS Security' },
  { key: 'ddos:view', label: 'View DDoS Simulations', group: 'DDoS Attack' },
  { key: 'ddos:run', label: 'Run DDoS Simulations', group: 'DDoS Attack' },
  { key: 'ddos:delete', label: 'Delete DDoS Simulations', group: 'DDoS Attack' },
  { key: 'phishing:view', label: 'View Phishing Simulations', group: 'Phishing Attack' },
  { key: 'phishing:run', label: 'Run Phishing Simulations', group: 'Phishing Attack' },
  { key: 'phishing:delete', label: 'Delete Phishing Simulations', group: 'Phishing Attack' },
  { key: 'camjam:view', label: 'View Camera IP Jam', group: 'Camera Jam' },
  { key: 'camjam:run', label: 'Run Camera IP Jam', group: 'Camera Jam' },
  { key: 'camjam:delete', label: 'Delete Camera IP Jam', group: 'Camera Jam' },
  { key: 'integrations:manage', label: 'Manage Integrations', group: 'Integrations' },
  { key: 'ai:chat', label: 'Use AI Chatbot', group: 'AI' },
  { key: 'ai:manage', label: 'Manage AI Settings', group: 'AI' },
  { key: 'aiimage:view', label: 'View AI Image Generator', group: 'AI Image' },
  { key: 'aiimage:generate', label: 'Generate AI Images', group: 'AI Image' },
  { key: 'aicode:view', label: 'View AI Code Workspace', group: 'AI Code' },
  { key: 'aicode:run', label: 'Run AI Code Generation', group: 'AI Code' },
  { key: 'roles:manage', label: 'Manage Roles', group: 'Admin' },
  { key: 'users:manage', label: 'Manage Users', group: 'Admin' },
];

export const ALL_PERMISSION_KEYS = PERMISSIONS.map((p) => p.key);

export const FEATURE_PERMISSIONS = {
  dashboard: 'dashboard:view',
  contacts: 'contacts:view',
  leads: 'leads:view',
  deals: 'deals:view',
  quotations: 'quotations:view',
  tasks: 'tasks:view',
  documents: 'documents:view',
  internships: 'internships:view',
  jobs: 'jobs:view',
  ats: 'ats:view',
  resumebuilder: 'resumebuilder:view',
  seo: 'seo:view',
  alertsms: 'alertsms:view',
  automation: 'automation:view',
  analytics: 'analytics:view',
  loadtest: 'loadtest:view',
  security: 'security:view',
  sechub: 'sechub:view',
  portscan: 'portscan:view',
  network: 'network:view',
  dnssec: 'dnssec:view',
  ddos: 'ddos:view',
  phishing: 'phishing:view',
  camjam: 'camjam:view',
  integrations: 'integrations:manage',
  ai: 'ai:chat',
  aiimage: 'aiimage:view',
  aicode: 'aicode:view',
  roles: 'roles:manage',
  users: 'users:manage',
};
